#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname $0)/.."

echo "Printing environment variables"
env

echo "Setting up aws-sdk layer"
. auto/layer

cd "../"

echo "Install serverless"
yarn add serverless

echo "Deploying notification-api"

export DEFAULT_AWS_REGION=ap-south-1
echo "Region => ${DEFAULT_AWS_REGION}"
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
echo "Access Key Id => ${AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
echo "Secret Access Key => ${AWS_SECRET_ACCESS_KEY}"
./node_modules/.bin/serverless deploy --config notification-api/serverless.yml -v
