#!/usr/bin/env bash

set -euox pipefail

cd "$(dirname $0)/.."

echo $PATH

echo "Printing environment variables"
env

echo "Setting up aws-sdk layer"
. auto/layer

echo "Install serverless"
yarn global add serverless --prefix /usr/local

echo "Deploying notification-api"
serverless deploy -v