#!/usr/bin/env bash

set -euox pipefail

cd "$(dirname $0)/../website/"

echo "Installing updates"
sudo apt-get update -y && sudo apt-get install awscli -y

echo "Updating index.html on shardulshreya.com "
aws s3 cp index.html s3://shardulshreya.com

echo "Updating index.html on www.shardulshreya.com"
aws s3 cp index.html s3://www.shardulshreya.com