#!/usr/bin/env bash

set -euox pipefail

cd "$(dirname $0)/../website/"

echo "Installing updates"
sudo apt-get update -y && sudo apt-get install awscli -y

export DEFAULT_AWS_REGION=ap-south-1
echo "Region => ${DEFAULT_AWS_REGION}"
export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
echo "Access Key Id => ${AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
echo "Secret Access Key => ${AWS_SECRET_ACCESS_KEY}"

echo "Updating index.html on shardulshreya.com "
aws s3 cp index.html s3://shardulshreya.com

echo "Updating index.html on www.shardulshreya.com"
aws s3 cp index.html s3://www.shardulshreya.com