#!/usr/bin/env bash

set -euox pipefail

cd "$(dirname $0)/.."

echo $PATH

echo "Installing update"
#sudo apt-get update -y && sudo apt-get install awscli -y

echo "Printing environment variables"
env

echo "Setting up aws-sdk layer"
. auto/layer

cd "../"

echo "Install serverless"
yarn add serverless

echo "Deploying notification-api"
./node_modules/.bin/serverless deploy --config notification-api/serverless.yml