#!/usr/bin/env bash

set -euox pipefail

cd "$(dirname $0)/.."

echo "Creating nodejs folder"
mkdir -p layer/nodejs

cd layer

echo "Deleting the contents if it exists already"
rm -rf nodejs/node_modules

echo "Installing packages"
yarn install --modules-folder nodejs/node_modules

#echo "Zipping the node_modules folder"
#zip -r aws-sdk.zip nodejs/
