name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy API
      run: ./auto/deploy-api
    - name: Deploy Website
      run: ./auto/deploy-website
